test: test

diff --git a/.github/workflows/dev-test.yml b/.github/workflows/dev-test.yml
--- a/.github/workflows/dev-test.yml
+++ b/.github/workflows/dev-test.yml
@@ -66,33 +66,41 @@ jobs:
         run: npm test -- --watch=false --browsers=ChromeHeadless
         working-directory: client
 
-  docker-test:
-    runs-on: ubuntu-latest
-    services:
-      docker:
-        image: docker:27.5.1
-        options: --privileged
-    if: startsWith(github.event.head_commit.message, 'test:')
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+  # TODO: uncomment if gh secrets are enabled for the project
+  # docker-test:
+  #   runs-on: ubuntu-latest
+  #   services:
+  #     docker:
+  #       image: docker:27.5.1
+  #       options: --privileged
+  #   if: startsWith(github.event.head_commit.message, 'test:')
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+  #     - name: Set environment variables
+  #       run: |
+  #         echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
+  #         echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
+  #         echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
+  #         echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
 
-      - name: Build and run stack with Docker Compose
-        run: docker compose up --build -d
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
 
-      - name: Wait for Spring Boot to become healthy
-        run: |
-          timeout=60
-          while [[ "$(docker inspect -f '{{.State.Health.Status}}' team-scrumbags-server)" != "healthy" ]]; do
-            sleep 5
-            timeout=$((timeout - 5))
-            if [ $timeout -le 0 ]; then
-              echo "Spring Boot failed to start in time"
-              docker logs team-scrumbags-server
-              exit 1
-            fi
-          done
-          echo "Spring Boot is healthy!"
+  #     - name: Build and run stack with Docker Compose
+  #       run: docker compose up --build -d
+
+  #     - name: Wait for Spring Boot to become healthy
+  #       run: |
+  #         timeout=60
+  #         while [[ "$(docker inspect -f '{{.State.Health.Status}}' team-scrumbags-server)" != "healthy" ]]; do
+  #           sleep 5
+  #           timeout=$((timeout - 5))
+  #           if [ $timeout -le 0 ]; then
+  #             echo "Spring Boot failed to start in time"
+  #             docker logs team-scrumbags-server
+  #             exit 1
+  #           fi
+  #         done
+  #         echo "Spring Boot is healthy!"
